export enum Constance {
    PERSONAL_INFORMATION = 'Personal information',
    EMAIL_NOTIFICATIONS = 'Email notifications',
    LET_US_GET_TO_KNOW_YOU = 'Let us get to know you',
    FIRST_NAME = 'First Name',
    LAST_NAME = 'Last Name',
    PHONE_NUMBER = 'Phone Number',
    EMAIL = 'Email',
    NEXT = 'Next',
    AVATAR = 'Avatar',
    CHANGE = 'Change',
    REMOVE = 'Remove',
    ORDER_STATUSES = 'Order statuses',
    PASSWORD_CHANGES = 'Password changes',
    SPECIAL_OFFERS = 'Special Offers',
    NEWSLETTER = 'Newsletter',
    LOG_OUT = 'Log out',
    DISCARD_CHANGES = 'Discard changes',
    SAVE_CHANGES = 'Save changes',
    BANNER_TITLE = 'Little Lemon',
    BANNER_SUBTITLE = 'Chicago',
    BANNER_DESCRIPTION = 'We are a family owned Mediterranean restaurant, focused on traditional recipes served with a modern twist.',
    ORDER_FOR_DELIVERY = 'ORDER FOR DELIVERY!',
};